# Generated by Django 3.1.1 on 2020-09-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=45)),
                ('gu', models.CharField(max_length=45)),
                ('location_users', models.ManyToManyField(blank=True, related_name='location_libraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_code', models.IntegerField(default=0)),
                ('lib_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('fax', models.CharField(max_length=45)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('homepage', models.CharField(max_length=45)),
                ('closed', models.CharField(max_length=45)),
                ('operating_time', models.CharField(max_length=45)),
                ('book_count', models.IntegerField(default=0)),
                ('library_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.librarylocation')),
            ],
        ),
    ]
