# Generated by Django 3.1.1 on 2020-09-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('vol', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsbnAdd1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=45)),
                ('target', models.CharField(max_length=45)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsbnAdd2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=45)),
                ('shape', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsbnAdd3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=45)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=45)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(default=0)),
                ('age', models.CharField(max_length=45)),
                ('ranking', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_count', models.IntegerField(default=0)),
                ('location', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.TextField()),
                ('hashtag_books', models.ManyToManyField(blank=True, related_name='book_hashtags', to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_add1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.isbnadd1'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_add2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.isbnadd2'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_add3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.isbnadd3'),
        ),
        migrations.AddField(
            model_name='book',
            name='kdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.kdc'),
        ),
    ]
