# Generated by Django 3.1.1 on 2020-09-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('birth', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('social', models.IntegerField(default=0)),
                ('social_id', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('gender', models.IntegerField(blank=True, default=0)),
                ('name', models.IntegerField(blank=True, default=0)),
                ('address', models.IntegerField(blank=True, default=0)),
                ('birth', models.IntegerField(blank=True, default=0)),
                ('calendar', models.IntegerField(blank=True, default=0)),
                ('favorite', models.IntegerField(blank=True, default=0)),
                ('review', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ManyToManyField(blank=True, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ManyToManyField(blank=True, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
